const NEWS_DAYS_DEPTH = 6;
const DATA_STORAGE_ARTICLES_KEY = 'articles';
const DATA_STORAGE_QUERY_KEY = 'keyword';
const FIELD_TITLE = 'title';
const FIELD_DESCRIPTION = 'description';

export {NEWS_DAYS_DEPTH, DATA_STORAGE_ARTICLES_KEY, DATA_STORAGE_QUERY_KEY, FIELD_TITLE, FIELD_DESCRIPTION}